In [1]:
# Importing dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
train =  pd.read_csv('train_ZoGVYWq.csv')
test = pd.read_csv('test_66516Ee.csv')

In [3]:
print('Train:', train.shape)
print('Test:', test.shape)

Train: (79853, 13)
Test: (34224, 12)


In [4]:
# for easy cleaning
dataset = [train,test]

In [5]:
train.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  renewal  
0                   13                C               Urban     3300        1  
1                   21                A               Urban    18000        1  
2                    7                C               Rural     3300        0  
3                    9                A               Urban     9600        1  
4                   12                B               Urban     9600        1

In [6]:
test.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0    649                             0.001        27384   51150   
1  81136                             0.124        23735  285140   
2  70762                             1.000        17170  186030   
3  53935                             0.198        16068  123540   
4  15476                             0.041        10591  200020   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    0.0                     0.0   
3                    0.0                     0.0   
4                    1.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.89   
1                             0.0                           98.93   
2                             0.0                             NaN   
3                             0.0                           99.00   
4                             0.0                           99.17   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  
0                    7                A               Rural     3300  
1                   19                A               Urban    11700  
2                    2                B               Urban    11700  
3                   11                B               Rural     5400  
4                   14                A               Rural     9600

In [7]:
train.columns

Index(['id', 'perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'Count_6-12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel', 'residence_area_type',
       'premium', 'renewal'],
      dtype='object')

In [8]:
# their is a problem with labeling of the dataset
#this columns are; Count_3-6_months_late, Count_6-12_months_late
for df in dataset:
    df.rename(index = str, columns = {'Count_3-6_months_late':'Count_3_6_months_late','Count_6-12_months_late':'Count_6_12_months_late'},inplace = True)


In [9]:
train.columns

Index(['id', 'perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3_6_months_late', 'Count_6_12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel', 'residence_area_type',
       'premium', 'renewal'],
      dtype='object')

In [10]:
test.columns

Index(['id', 'perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3_6_months_late', 'Count_6_12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel', 'residence_area_type',
       'premium'],
      dtype='object')

# Handle null values

In [11]:
train.isnull().any(axis = 0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late                True
Count_6_12_months_late               True
Count_more_than_12_months_late       True
application_underwriting_score       True
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
premium                             False
renewal                             False
dtype: bool

In [12]:
test.isnull().any(axis=0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late                True
Count_6_12_months_late               True
Count_more_than_12_months_late       True
application_underwriting_score       True
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
premium                             False
dtype: bool

In [13]:
# fill null values
for df in dataset:
    df['Count_3_6_months_late'].fillna(train.Count_3_6_months_late.median(), inplace = True)
    df['Count_6_12_months_late'].fillna(train.Count_6_12_months_late.median(), inplace = True)
    df['Count_more_than_12_months_late'].fillna(train.Count_more_than_12_months_late.median(), inplace = True)
    df['application_underwriting_score'].fillna(train.application_underwriting_score.median(), inplace = True)

In [14]:
test.isnull().any(axis=0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late               False
Count_6_12_months_late              False
Count_more_than_12_months_late      False
application_underwriting_score      False
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
premium                             False
dtype: bool

In [15]:
train.isnull().any(axis=0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late               False
Count_6_12_months_late              False
Count_more_than_12_months_late      False
application_underwriting_score      False
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
premium                             False
renewal                             False
dtype: bool

In [16]:
# a little feature engineering
#lets calculate monthly premium paid per number of premium paid
train['premium_per_premium_paid'] = train.premium/train.no_of_premiums_paid
test['premium_per_premium_paid'] = test.premium/test.no_of_premiums_paid

In [17]:
train.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3_6_months_late  Count_6_12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  renewal  \
0                   13                C               Urban     3300        1   
1                   21                A               Urban    18000        1   
2                    7                C               Rural     3300        0   
3                    9                A               Urban     9600        1   
4                   12                B               Urban     9600        1   

   premium_per_premium_paid  
0                253.846154  
1                857.142857  
2                471.428571  
3               1066.666667  
4                800.000000

In [18]:
test.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0    649                             0.001        27384   51150   
1  81136                             0.124        23735  285140   
2  70762                             1.000        17170  186030   
3  53935                             0.198        16068  123540   
4  15476                             0.041        10591  200020   

   Count_3_6_months_late  Count_6_12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    0.0                     0.0   
3                    0.0                     0.0   
4                    1.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.89   
1                             0.0                           98.93   
2                             0.0                           99.21   
3                             0.0                           99.00   
4                             0.0                           99.17   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  \
0                    7                A               Rural     3300   
1                   19                A               Urban    11700   
2                    2                B               Urban    11700   
3                   11                B               Rural     5400   
4                   14                A               Rural     9600   

   premium_per_premium_paid  
0                471.428571  
1                615.789474  
2               5850.000000  
3                490.909091  
4                685.714286

In [19]:
# Separete training set and testing set
X = train.drop(('renewal'),axis=1)
X = X.drop(('id'),axis=1).values

y = train.iloc[:,12].values


In [20]:
X

array([[0.429, 12058, 355060, ..., 'Urban', 3300, 253.84615384615384],
       [0.01, 21546, 315150, ..., 'Urban', 18000, 857.1428571428571],
       [0.917, 17531, 84140, ..., 'Rural', 3300, 471.42857142857144],
       ...,
       [0.0, 23372, 305020, ..., 'Rural', 9600, 800.0],
       [0.39799999999999996, 22641, 39330, ..., 'Rural', 5700, 712.5],
       [0.55, 15709, 280140, ..., 'Urban', 9600, 1200.0]], dtype=object)

In [21]:
y

array([1, 1, 0, ..., 1, 1, 0])

In [22]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 9] = labelencoder.fit_transform(X[:, 9])
X[:, 8] = labelencoder.fit_transform(X[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
X = onehotencoder.fit_transform(X).toarray()

In [23]:
X[:, 8]

array([0., 0., 2., ..., 0., 0., 1.])

In [24]:
# splitting data into training set and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 0)



In [25]:
print('X_train',X_train.shape)
print('X_test',X_test.shape)
print('y_train',y_train.shape)
print('y_test',y_test.shape)

X_train (63882, 16)
X_test (15971, 16)
y_train (63882,)
y_test (15971,)


In [26]:
X_train

array([[1.00e+00, 0.00e+00, 0.00e+00, ..., 1.00e+00, 1.20e+03, 3.00e+02],
       [0.00e+00, 0.00e+00, 1.00e+00, ..., 1.00e+00, 3.30e+03, 1.32e+02],
       [0.00e+00, 0.00e+00, 0.00e+00, ..., 1.00e+00, 1.17e+04, 7.80e+02],
       ...,
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 1.00e+00, 1.17e+04, 1.17e+03],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+00, 1.17e+04, 1.30e+03],
       [0.00e+00, 0.00e+00, 1.00e+00, ..., 1.00e+00, 1.17e+04, 9.75e+02]])

In [27]:
# Scaling the dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Modeling 

In [28]:
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
from time import time

In [29]:
# Applying k-Fold Cross Validation to evaluate the model
def k_fold(model,X_train,y_train):
    accuracies = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 10)
    print('K-Fold cross validation mean:',accuracies.mean())
    print('K-Fold cross validation std:',accuracies.std()) 
    

In [30]:
# LogisticRegression classifier
def logistic_classfier(features, labels, **kwargs):
    ''' a function of logistic regression that will fit the classier to the data,
    make prediction and print a classification report'''
    
    print('==================================')
    print('Fitting logistic classifier')
    print('==================================')
    
    # instantiate model
    model_1 = LogisticRegression(random_state=0)
    
    # train model
    start = time()
    model_1.fit(features, labels)
    end = time()
    
    # Training time
    print('Training time:',end-start)
    
    # Making predictions
    y_pred = model_1.predict(X_test)
    
    # get a sense of performance
    accuracy_1 = classification_report(y_test,y_pred)
    print('Accuracy:',accuracy_1)
    
    cm = confusion_matrix(y_test,y_pred)
    print('Confusion matrix:')
    print(cm)
    
    k_fold(model_1,features,labels)
    

    
    return model_1

# RandomForest classifier
def random_forest_classfier(features, labels, **kwargs):
    ''' a function of Random Forest that will fit the classier to the data,
    make prediction and print a classification report'''  
    
    print('==================================')
    print('Fitting RandomForest classifier')
    print('==================================')
    
    # instantiate model
    model_2 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    
    # train model
    start = time()
    model_2.fit(features, labels) 
    end = time()
    
    # Training time
    print('Training time:',end-start)  
    # Making prediction
    
    y_pred = model_2.predict(X_test)
    
    # get a  sense of performance
    accuracy_2 = classification_report(y_test,y_pred)
    print('Accuracy:',accuracy_2)
    
    cm = confusion_matrix(y_test,y_pred)
    print('Confusion matrix:')
    print(cm)
    
    k_fold(model_2,features,labels)

    
    return model_2
    
# Decision tree classifier
def decision_tree_classifier(features, labels, **kwargs):
    ''' a function of xgboost that will fit the classier to the data,
    make prediction and print a classification report'''  
    
    print('==================================')
    print('Decision classfier classifier')
    print('==================================')
    
    # instantiate model
    model_3 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    
    # train model
    start = time()
    model_3.fit(features, labels) 
    end = time()
       
    # Training time
    print('Training time:',end-start) 
    
    # Making prediction
    y_pred = model_3.predict(X_test)
    
    # get a sense of performance
    accuracy_3 = classification_report(y_test,y_pred)
    print('Decision tree accuracy:',accuracy_3)
    
    cm = confusion_matrix(y_test,y_pred)
    print('Confusion matrix:')
    print(cm)
    
    k_fold(model_3,features,labels)
    
    return model_3

In [31]:
model_a =  logistic_classfier(X_train,y_train)
print(model_a)

Fitting logistic classifier
Training time: 0.4453239440917969
Accuracy:              precision    recall  f1-score   support

          0       0.55      0.13      0.21       977
          1       0.95      0.99      0.97     14994

avg / total       0.92      0.94      0.92     15971

Confusion matrix:
[[  125   852]
 [  103 14891]]
K-Fold cross validation mean: 0.9390594747781197
K-Fold cross validation std: 0.0011440454089608045
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [32]:
model_b = random_forest_classfier(X_train,y_train)
print(model_b)

Fitting RandomForest classifier
Training time: 2.3179612159729004
Accuracy:              precision    recall  f1-score   support

          0       0.39      0.17      0.24       977
          1       0.95      0.98      0.96     14994

avg / total       0.91      0.93      0.92     15971

Confusion matrix:
[[  166   811]
 [  263 14731]]
K-Fold cross validation mean: 0.933611970998047
K-Fold cross validation std: 0.0016588756448864222
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)


In [33]:
model_c = decision_tree_classifier(X_train,y_train)
print(model_c)

Decision classfier classifier
Training time: 1.2136297225952148
Decision tree accuracy:              precision    recall  f1-score   support

          0       0.21      0.25      0.23       977
          1       0.95      0.94      0.95     14994

avg / total       0.91      0.90      0.90     15971

Confusion matrix:
[[  242   735]
 [  889 14105]]
K-Fold cross validation mean: 0.8978901755345262
K-Fold cross validation std: 0.004041463226566219
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')


In [34]:
# seems we will be working with logistic regression
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.1,1, 10, 100],'penalty': ['l1','l2']}]
grid_search = GridSearchCV(estimator = model_a,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
best_model = grid_search.best_estimator_

print('best accuracy',best_accuracy)
print('best parameters',best_parameters)

best accuracy 0.9390908237062083
best parameters {'C': 0.1, 'penalty': 'l1'}


# Final predictions for submissions

In [35]:
test.columns

Index(['id', 'perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3_6_months_late', 'Count_6_12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel', 'residence_area_type',
       'premium', 'premium_per_premium_paid'],
      dtype='object')

In [37]:
Validation = test.drop(('id'),axis = 1).values

In [38]:
test.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0    649                             0.001        27384   51150   
1  81136                             0.124        23735  285140   
2  70762                             1.000        17170  186030   
3  53935                             0.198        16068  123540   
4  15476                             0.041        10591  200020   

   Count_3_6_months_late  Count_6_12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    0.0                     0.0   
3                    0.0                     0.0   
4                    1.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.89   
1                             0.0                           98.93   
2                             0.0                           99.21   
3                             0.0                           99.00   
4                             0.0                           99.17   

   no_of_premiums_paid sourcing_channel residence_area_type  premium  \
0                    7                A               Rural     3300   
1                   19                A               Urban    11700   
2                    2                B               Urban    11700   
3                   11                B               Rural     5400   
4                   14                A               Rural     9600   

   premium_per_premium_paid  
0                471.428571  
1                615.789474  
2               5850.000000  
3                490.909091  
4                685.714286

In [39]:
Validation

array([[0.001, 27384, 51150, ..., 'Rural', 3300, 471.42857142857144],
       [0.124, 23735, 285140, ..., 'Urban', 11700, 615.7894736842105],
       [1.0, 17170, 186030, ..., 'Urban', 11700, 5850.0],
       ...,
       [0.325, 18264, 196570, ..., 'Rural', 1200, 85.71428571428571],
       [0.983, 16798, 212150, ..., 'Urban', 13800, 1380.0],
       [0.005, 24467, 89190, ..., 'Urban', 5400, 490.90909090909093]],
      dtype=object)

In [40]:
# Encoding validation dataset
Validation[:, 9] = labelencoder.fit_transform(Validation[:, 9])
Validation[:, 8] = labelencoder.fit_transform(Validation[:, 8])
onehotencoder = OneHotEncoder(categorical_features = [8])
Validation = onehotencoder.fit_transform(Validation).toarray()

In [41]:
# scaling validation dataset
Validation = scaler.transform(Validation)

In [42]:
prediction_proba = best_model.predict_proba(Validation)

In [43]:
prediction_proba

array([[0.01025108, 0.98974892],
       [0.02187682, 0.97812318],
       [0.12342406, 0.87657594],
       ...,
       [0.04028193, 0.95971807],
       [0.25364865, 0.74635135],
       [0.02658734, 0.97341266]])

In [44]:
final_prediction = pd.DataFrame()

In [45]:
final_prediction['id'] = test.id
final_prediction['renewal'] = prediction_proba[:,1]  #probability of renewal

In [46]:
final_prediction.head()

id   renewal
0    649  0.989749
1  81136  0.978123
2  70762  0.876576
3  53935  0.970145
4  15476  0.956428

# Calculating incentives from the given formulae

In [47]:
#creating a dataset a with values of delta_p
import numpy as np
x = pd.DataFrame(np.arange(0,1000,10), columns=['incentive'])
x['delta_p'] = 0.2*(1-np.exp(-2*(1-np.exp(-x['incentive']/400))))

# calculating optimised premium
final_prediction['opt_premium'] = test['premium']*final_prediction['renewal']

In [48]:
x.head()

incentive   delta_p
0          0  0.000000
1         10  0.009636
2         20  0.018587
3         30  0.026911
4         40  0.034662

In [49]:
final_prediction.head()

id   renewal   opt_premium
0    649  0.989749   3266.171430
1  81136  0.978123  11444.041233
2  70762  0.876576  10255.938473
3  53935  0.970145   5238.781085
4  15476  0.956428   9181.706263

In [57]:
#finding values with maximum delta revenue
f = []
r = []
for i in range(test.shape[0]):
    n = test.iloc[i,-1]
    p = test.iloc[i,-2]
    x['total_revenue'] = (n + (x['delta_p'])*n) - (x['incentive']) 
    x['tot_p'] = p + (p * (x['delta_p']))
    #y = x[x.tot_p <=1.000000]
    y = x.sort_values(['total_revenue'], ascending=False)
    incen = y.iloc[0, 0]
    f.append(incen)
    rev = y.iloc[0,2]
    r.append(rev)

In [53]:
#appending final prediction dataset
final_prediction['incentive'] = f
final_prediction['reven'] =r

In [54]:
final_prediction.head()

id   renewal   opt_premium  incentive        reven
0    649  0.989749   3266.171430          0   471.428571
1  81136  0.978123  11444.041233          0   615.789474
2  70762  0.876576  10255.938473        290  6312.865728
3  53935  0.970145   5238.781085          0   490.909091
4  15476  0.956428   9181.706263          0   685.714286

In [61]:
# will only submit prediction with id,renewal and incentive
submission = final_prediction.iloc[:,[0,1,3]]

In [62]:
submission.head()

id   renewal  incentive
0    649  0.989749          0
1  81136  0.978123          0
2  70762  0.876576        290
3  53935  0.970145          0
4  15476  0.956428          0

In [63]:
# Creating submission file
submission.to_csv("submission.csv", index = False)